### ISSUE TITLE
[2024.01.31] tier4_metrics_rviz_plugin fails to build due to missing dependency (libqt5-charts-dev)

### ISSUE THREAD

**Issue by esteve** [autowarefoundation/autoware-deb-packages#66]

**Comment by esteve** [comment]
See https://github.com/autowarefoundation/autoware.universe/pull/6321

**Comment by satoshi-ota** [comment]
I added an ansible task in autoware repo in [**this**](https://github.com/autowarefoundation/autoware/pull/4119) PR. So, please update your autoware env with `setup-dev-env.sh`.

**Comment by esteve** [comment]
@satoshi-ota Thanks, but the buildfarm does not use Ansible at all, please read my previous comment which has a link to a PR that fixes this issue in Autoware.universe
